development:
  adapter: postgresql
  encoding: unicode
  database: tickets_development
  pool: 5
  host: localhost
  username: misha
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: tickets_test
  pool: 5
  host: localhost
  username: misha
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: tickets_production
  pool: 5
  host: localhost
  username: misha
  password:
